queue_rules:
  - name: default
    conditions:
      - status-success=run-tests / check-conventional-commits / check-conventional-commits
      - status-success=run-tests / cargo-audit
      - status-success=run-tests / cargo-test (macos-latest)
      - status-success=run-tests / cargo-test (ubuntu-latest)
      - status-success=run-tests / cargo-test (windows-latest)
      - status-success=run-tests / lint (ubuntu-latest)
      - status-success=run-tests / lint (windows-latest)

pull_request_rules:
  - name: automatic rebase for dependencies
    conditions:
      - status-success=run-tests / check-conventional-commits / check-conventional-commits
      - status-success=run-tests / cargo-audit
      - status-success=run-tests / cargo-test (macos-latest)
      - status-success=run-tests / cargo-test (ubuntu-latest)
      - status-success=run-tests / cargo-test (windows-latest)
      - status-success=run-tests / lint (ubuntu-latest)
      - status-success=run-tests / lint (windows-latest)
      - base=master
      - author=dependabot[bot]
    actions:
      queue:
        method: merge
        name: default




