[package]
name = "specdown"
version = "0.1.0"
authors = ["Tom Oram <me@tomoram.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
comrak = "0.7"
nom = "5"

[dev-dependencies]
assert_cmd = "1.0.1"
indoc = "0.3"