tag_prefix = "v"
from_latest_tag = true
ignore_merge_commits = true
branch_whitelist = ["master"]
pre_bump_hooks = [
    '''sed 's/^version = "[^"]*"/version = "{{version}}"/' Cargo.toml >Cargo.toml.new''',
    'mv Cargo.toml.new Cargo.toml'
]
post_bump_hooks = [
    "git push",
    "git push origin v{{version}}",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "specdown"
owner = "specdown"
