tag_prefix = "v"
from_latest_tag = false
ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = [
    "cargo bump {{version}}"
]
post_bump_hooks = [
    "git push",
    "git push origin v{{version}}",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "specdown"
owner = "specdown"
